---
version: '3.8'
services:
  # Has a connection to all networks.
  # Can ping everyone.
  pc1:
    image: alpine:3.14.2
    container_name: pc1
    command: ping -c20 pc2
    networks:
      - headquarters
      - branch1
      - branch2

  # Only connected to pc1
  # Cannot ping pc3
  pc2:
    image: alpine:3.14.2
    container_name: pc2
    command: ping -c20 pc3
    networks:
      - branch1

  # Only connected to pc1
  # Cannot ping pc2
  pc3:
    image: alpine:3.14.2
    container_name: pc3
    command: ping -c20 pc1
    networks:
      - branch2

networks:
  headquarters:
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/29

  branch1:
    ipam:
      driver: default
      config:
        - subnet: 10.2.2.0/29

  branch2:
    ipam:
      driver: default
      config:
        - subnet: 10.3.3.0/29
...